#!/usr/bin/env python3

"""Generate AUTHORS.md from scripts/contributors.yml plus git history.

AUTHORS.md is a generated file: edit scripts/contributors.yml to change the
curated sections, and .mailmap to fold an author's alternate git identities
together, then re-run this script.
"""

from pathlib import Path
import subprocess
import sys
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
CONFIG = SCRIPT_DIR / "contributors.yml"
OUTPUT = REPO_ROOT / "AUTHORS.md"

GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate-authors.py. Do not edit by hand: your\n"
    "     changes will be overwritten. Edit scripts/contributors.yml instead. -->"
)

DEFAULT_INTRO = (
    "Cumulative record of everyone who has contributed to MOSE. Names are never\n"
    "removed from this file; per-release credit is recorded in `CITATION.cff`."
)


def normalize_people(items):
    people = []

    for item in items:
        if isinstance(item, str):
            people.append({"name": item, "role": ""})
            continue

        if isinstance(item, dict) and "name" in item:
            people.append(
                {
                    "name": item["name"],
                    "role": item.get("role", ""),
                }
            )

    return people


def render_section(title, people, note=None):
    """Render a '## title' section, or nothing at all when there is nobody in it."""
    if not people:
        return ""

    lines = ["## {}\n\n".format(title)]

    if note:
        lines.append("{}\n\n".format(note))

    for p in people:
        if p["role"]:
            lines.append("- {} - {}\n".format(p["name"], p["role"]))
        else:
            lines.append("- {}\n".format(p["name"]))

    lines.append("\n")

    return "".join(lines)


if not CONFIG.exists():
    sys.exit("error: missing config file {}".format(CONFIG))

with open(CONFIG, "r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f) or {}

intro = str(cfg.get("intro", DEFAULT_INTRO)).strip()
original_authors = normalize_people(cfg.get("original_authors", []))
maintainers = normalize_people(
    cfg.get("present_maintainers", cfg.get("maintainers", []))
)
alumni = normalize_people(cfg.get("alumni", []))
exclude = [str(e).lower() for e in cfg.get("exclude", [])]

def shortlog(extra_args):
    return subprocess.check_output(
        ["git", "shortlog", "-sne", "--all"] + extra_args,
        cwd=str(REPO_ROOT),
        universal_newlines=True,
    )


# Counting Co-authored-by trailers keeps squash-merged pull requests from
# silently dropping every author but the one who opened them. Needs git 2.29+.
try:
    result = shortlog(["--group=author", "--group=trailer:co-authored-by"])
except subprocess.CalledProcessError:
    print("warning: git too old for --group, co-authors will be missed")
    result = shortlog([])

contributors = []

for line in result.splitlines():
    line = line.strip()

    if not line or "\t" not in line:
        continue

    _, identity = line.split("\t", 1)

    # Drop bots and opted-out identities. Matching the whole "Name <email>"
    # string means one exclude entry covers both the name and the address.
    if any(e in identity.lower() for e in exclude):
        continue

    contributors.append(identity.split("<")[0].strip())

curated = (
    {m["name"] for m in maintainers}
    | {a["name"] for a in original_authors}
    | {a["name"] for a in alumni}
)

contributors = normalize_people(sorted(set(contributors) - curated))

document = [
    "# Authors\n\n",
    "{}\n\n".format(GENERATED_NOTICE),
]

if intro:
    document.append("{}\n\n".format(intro))

document.append(render_section("Original Authors", original_authors))
document.append(render_section("Present Maintainers", maintainers))
document.append(
    render_section(
        "Contributors",
        contributors,
        note="Automatically sourced from git history.",
    )
)
document.append(render_section("Alumni", alumni))

OUTPUT.write_text("".join(document).rstrip("\n") + "\n", encoding="utf-8")

print("Generated {}".format(OUTPUT))
