"""Independent low-Mach mixture-averaged (multicomponent) reference for the 1D
diffusion test, with Cantera.

Apples-to-apples ground truth for MOSE run with the *multicomponent* species-
diffusion model (input.ini: Sc <= 0), where every species k gets its own
mixture-averaged (Curtiss-Hirschfelder) diffusion coefficient

    D_k = (1 - X_k) / sum_{j!=k} ( X_j / D_kj )          [Cantera: mix_diff_coeffs]

with binary coefficients D_kj from kinetic theory.  This is exactly the closure
MOSE evaluates in co_DS (its diffusion.dat table is generated by Cantera at the
same reference pressure), so any difference here is purely numerical.

This reference reproduces MOSE's *discrete* model term by term
(src/lib/numerics/fluxes/Lib_Diffusive.f90):

  * species flux uses the MASS-fraction gradient with the mixture-averaged D_k,
        j_k = - rho D_k dY_k/dx                                       (eq. flux)
    closed by the mass-conservation correction velocity so that sum_k j_k = 0,
        j_k <- j_k - Y_k sum_l j_l                                    (Lib_Diffusive:155)
  * energy carries conductivity + the (uncorrected) inter-species enthalpy flux,
        q = - k dT/dx - rho sum_k h_k D_k dY_k/dx                     (Lib_Diffusive:151,161)
    with k the full Wilke mixture conductivity (MOSE Prl<=0; default in this case).

Low-Mach coupling is identical to reference_unity_lewis.py: the T/composition
contrast makes the gas expand, inducing a dilatational velocity that advects the
scalars (what MOSE's compressible solver carries).  At constant thermodynamic
pressure p0, continuity + ideal-gas EOS fix the divergence (rho = p0 W/(Ru T)):

    div u = D ln T/Dt - D ln W/Dt
          = [ Lh - sum_k h_k LY_k ] / (rho cp T)  +  W sum_k (LY_k / W_k) / rho

where LY_k = d(rho Y_k)/dt|_diff and Lh = d(rho h)/dt|_diff are the multicomponent
diffusion operators above.  This relation is closure-independent (derived only from
continuity + EOS), so the same form as the unity-Lewis reference applies here with
the multicomponent LY_k / Lh.

Solved with Cantera (GRI30, mixture-averaged transport) on the same grid as MOSE
(200 cells, L=0.05 m, periodic), constant p=101325 Pa.

Importable: solve(t_end, N, advection=True) -> (xc, T, Y_CH4).  advection=False
recovers the zero-velocity diffusion limit.  Run as a script to also dump CSVs.
"""
import numpy as np
import cantera as ct
from pathlib import Path

# ---- setup (matches build_ic.py / input.ini) ------------------------------
L      = 0.05
p0     = 101325.0
x0     = 25e-3
d      = 2.5e-3
SP     = ['CH4', 'H2O', 'N2', 'O2']
Y_ox   = {'CH4': 0.0,   'H2O': 0.1, 'N2': 0.758, 'O2': 0.142}   # f=0 (center)
Y_fu   = {'CH4': 0.214, 'H2O': 0.0, 'N2': 0.591, 'O2': 0.195}   # f=1 (edges)
T_ox, T_fu = 1350.0, 320.0


def solve(t_end, N=200, cfl=0.3, advection=True, dk_form='mose', return_full=False):
    """Integrate the low-Mach mixture-averaged problem to t_end.

    Returns xc[m], T[K], Y_CH4 (N,) by default; with return_full=True returns the whole
    mass-fraction array Y (N, nsp) in SP order [CH4, H2O, N2, O2] instead of Y_CH4.
    advection=True adds the dilatational velocity induced by thermal expansion
    (apples-to-apples with MOSE); advection=False is the pure zero-velocity limit.

    dk_form selects the mixture-averaged coefficient definition (both built from the
    SAME binary D_kj, so the difference is purely the numerator):
      'mose'    : D_k = (1 - X_k) / sum_{j!=k} X_j/D_kj   (Curtiss-Hirschfelder,
                  mole-fraction numerator) -- this is exactly what MOSE's co_DS does.
      'cantera' : D_k = mix_diff_coeffs = (1 - Y_k)/sum_{j!=k} X_j/D_kj  (Chemkin/Kee
                  mass-fraction numerator) -- Cantera's standard mixture-averaged model.
    Use 'mose' to isolate numerics against MOSE; 'cantera' to measure MOSE's model
    offset from the Chemkin/Cantera standard.
    """
    gas = ct.Solution('gri30.yaml')
    ksp = [gas.species_index(s) for s in SP]
    Wk  = gas.molecular_weights[ksp]            # kg/kmol, per tracked species
    nsp = len(SP)
    dx  = L / N
    xc  = (np.arange(N) + 0.5) * dx
    f   = 1.0 - np.exp(-((xc - x0) ** 2) / d ** 2)

    Y = np.zeros((N, nsp))
    for j, s in enumerate(SP):
        Y[:, j] = Y_ox[s] + (Y_fu[s] - Y_ox[s]) * f
    T = T_ox + (T_fu - T_ox) * f

    full = np.zeros(gas.n_species)

    def state_from_hY(h, Y):
        """Properties at (h, p0, Y): T, rho, mu, cp, W, k, D_k(N,nsp), h_k(N,nsp)."""
        Tc  = np.empty(N); rho = np.empty(N); cp = np.empty(N); W = np.empty(N)
        kc  = np.empty(N); D = np.empty((N, nsp)); hk = np.empty((N, nsp))
        for i in range(N):
            full[:] = 0.0; full[ksp] = Y[i]
            gas.HPY = h[i], p0, full
            Tc[i] = gas.T; rho[i] = gas.density; cp[i] = gas.cp_mass
            W[i] = gas.mean_molecular_weight; kc[i] = gas.thermal_conductivity
            if dk_form == 'cantera':
                D[i] = gas.mix_diff_coeffs[ksp]              # (1-Y_k)/sum X_j/D_kj
            else:
                # MOSE co_DS: (1-X_k)/sum_{j!=k} X_j/D_kj from the binary coeffs
                Bd = gas.binary_diff_coeffs                  # (n,n) m^2/s
                Xk = gas.X[ksp]
                for a in range(nsp):
                    den = 0.0
                    for b in range(nsp):
                        if b != a:
                            den += Xk[b] / Bd[ksp[a], ksp[b]]
                    D[i, a] = (1.0 - Xk[a]) / den if den > 0.0 else Bd[ksp[a], ksp[a]]
            hk[i] = gas.partial_molar_enthalpies[ksp] / Wk   # J/kg per species
        return Tc, rho, cp, W, kc, D, hk

    def diffusion_operators(Y, T, rho, kc, D, hk):
        """MOSE multicomponent LY_k (corrected) and Lh (cond + uncorrected enthalpy).

        Face fluxes on the periodic grid; face = i+1/2 (right of cell i).
        """
        rhoD = rho[:, None] * D                              # (N,nsp)
        rhoDf = 0.5 * (rhoD + np.roll(rhoD, -1, axis=0))     # face value
        gradY = (np.roll(Y, -1, axis=0) - Y) / dx            # face dY/dx
        Fr = rhoDf * gradY                                   # uncorrected species flux

        # mass-conservation correction velocity (MOSE: Flux -= sum(Flux)*Y/rho)
        Yf = 0.5 * (Y + np.roll(Y, -1, axis=0))              # face mass fractions
        Jr = Fr - Yf * Fr.sum(axis=1, keepdims=True)         # corrected species flux
        LY = (Jr - np.roll(Jr, 1, axis=0)) / dx              # (N,nsp)

        # energy: conductivity + uncorrected inter-species enthalpy flux
        kf = 0.5 * (kc + np.roll(kc, -1))
        Qr = kf * (np.roll(T, -1) - T) / dx                  # conductive face flux
        hkf = 0.5 * (hk + np.roll(hk, -1, axis=0))           # face species enthalpy
        Hr = (hkf * Fr).sum(axis=1)                          # enthalpy diffusion flux
        Hflux = Qr + Hr
        Lh = (Hflux - np.roll(Hflux, 1)) / dx
        return LY, Lh

    def upwind_div(q, uf):
        """d/dx( u q ) with first-order upwind face values (q a conserved density)."""
        flux = np.where(uf >= 0.0, uf * q, uf * np.roll(q, -1))
        return (flux - np.roll(flux, 1)) / dx

    # conservative state: partial densities U_k = rho Y_k, total enthalpy E = rho h
    full[:] = 0.0
    rho0 = np.empty(N); h0 = np.empty(N)
    for i in range(N):
        full[ksp] = Y[i]
        gas.TPY = T[i], p0, full
        rho0[i] = gas.density; h0[i] = gas.enthalpy_mass
    U = rho0[:, None] * Y
    E = rho0 * h0

    t = 0.0
    while t < t_end:
        rho = U.sum(axis=1)
        Y   = U / rho[:, None]
        h   = E / rho
        T, rho, cp, W, kc, D, hk = state_from_hY(h, Y)

        # stable explicit step: limited by the fastest diffusivity (species or thermal)
        alpha = kc / (rho * cp)
        dmax = max(D.max(), alpha.max())
        dt = min(cfl * dx * dx / dmax, t_end - t)

        LY, Lh = diffusion_operators(Y, T, rho, kc, D, hk)

        # advance diffusion (conservative; sum_k LY_k == 0 keeps continuity)
        U += dt * LY
        E += dt * Lh

        if advection:
            S = (Lh - (hk * LY).sum(axis=1)) / (rho * cp * T) \
                + W * (LY / Wk).sum(axis=1) / rho
            S -= S.mean()                                # enforce periodicity (p0 fixed)
            uf = np.cumsum(S) * dx                        # u at face i+1/2, u_{-1/2}=0
            uf -= uf.mean()                               # remove arbitrary mean velocity
            for j in range(nsp):
                U[:, j] -= dt * upwind_div(U[:, j], uf)
            E -= dt * upwind_div(E, uf)

        t += dt

    rho = U.sum(axis=1)
    Y   = U / rho[:, None]
    h   = E / rho
    for i in range(N):
        full[:] = 0.0; full[ksp] = Y[i]
        gas.HPY = h[i], p0, full
        T[i] = gas.T
    return (xc, T, Y) if return_full else (xc, T, Y[:, 0])


if __name__ == '__main__':
    import sys
    t_end = float(sys.argv[1]) if len(sys.argv) > 1 else 50e-3
    xc, T, Y_CH4 = solve(t_end)
    ref = Path(__file__).resolve().parent / 'reference'
    ref.mkdir(exist_ok=True)
    lab = f"{t_end*1e3:g}ms"
    np.savetxt(ref / f'CH4_mc_{lab}.csv', np.column_stack([xc, Y_CH4]), delimiter=',')
    np.savetxt(ref / f'T_mc_{lab}.csv',   np.column_stack([xc, T]),     delimiter=',')
    N = len(xc)
    print(f"Cantera low-Mach mixture-averaged reference @ {t_end*1e3:.1f} ms")
    print(f"  Y_CH4 center={Y_CH4[N//2]:.4f}  edge={Y_CH4[0]:.4f}")
    print(f"  T     center={T[N//2]:.1f} K  edge={T[0]:.1f} K")
    print(f"  wrote {ref}/CH4_mc_{lab}.csv, T_mc_{lab}.csv")
